@echo off
set project=Torch
set build_path=F:\1hise projects\Plasma - Copy\tabbedInterface\Binaries
set msbuild="C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\MSBuild\15.0\Bin\MsBuild.exe"
set vs_args=/p:Configuration="Release" /verbosity:minimal
set PreferredToolArchitecture=x64
set VisualStudioVersion=15.0

"H:\HISE-master\HISE-master\tools\Projucer\Projucer.exe" --resave "%build_path%\AutogeneratedProject.jucer"

echo Compiling 64bit Instrument plugin %project% ...
set Platform=X64
%msbuild% "%build_path%\Builds\VisualStudio2017\%project%.sln" %vs_args%



pause
